# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/invoicedb
spring.datasource.username=invoiceuser
spring.datasource.password=invoicepass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Mail (placeholder for now)
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587

# App
app.jwt.secret=changethislatertoaverylongsecretkeyforproduction
app.jwt.expiration=86400000

#Security
spring.security.user.name=admin
spring.security.user.password=admin